/**
 * lib/mockData.ts
 *
 * Real, active curated opportunities from Unstop, Devfolio, HackerEarth, and H2Skill.
 * Used as high-fidelity seed data when Supabase is not yet populated
 * so all "Apply Now" links redirect to live, active listings.
 */

import type { OpportunityRow, CourseRow } from "./supabase/types"

export const MOCK_OPPORTUNITIES: OpportunityRow[] = [
  {
    id: "unstop-buildsprint-ai",
    title: "BuildSprint 2026 — Next-Gen AI Hackathon",
    description: "BuildSprint is a fast-paced technology sprint organized on Unstop. Compete against top engineering teams to build cutting-edge solutions, AI agents, and full-stack platforms with mentorship and prize pools.",
    type: "hackathon",
    source_platform: "Unstop",
    source_url: "https://unstop.com/hackathons/buildsprint-latentforceai-1742504",
    organizer: "Latent Force AI & Unstop",
    location: "Online",
    mode: "online",
    start_date: "2026-09-01T00:00:00Z",
    end_date: "2026-10-15T23:59:59Z",
    application_deadline: "2026-09-30T18:29:59Z",
    prize_pool: "₹250,000 + Swags",
    stipend: null,
    tags: ["AI/ML", "Python", "Full Stack", "Cloud", "FastAPI"],
    eligibility: "Open to all engineering students and developers across India",
    team_size: "1 - 4 Members",
    banner_image_url: "https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/banner/6a83305e76ae6_hackcelestial-30.png",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-20T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "devfolio-fusionix-2026",
    title: "FusioniX 2026 — Asia's Premier Innovation Hackathon",
    description: "Join developers, designers, and builders for 36 hours of non-stop building at FusioniX on Devfolio. Build decentralized applications, zero-knowledge proofs, AI systems, and Web3 infrastructure with top mentors.",
    type: "hackathon",
    source_platform: "Devfolio",
    source_url: "https://fusionix-1.devfolio.co",
    organizer: "Devfolio Community",
    location: "Online / Hybrid",
    mode: "hybrid",
    start_date: "2026-10-10T09:00:00Z",
    end_date: "2026-10-12T18:00:00Z",
    application_deadline: "2026-09-25T18:29:59Z",
    prize_pool: "$50,000+",
    stipend: null,
    tags: ["Web3", "Solidity", "AI Agents", "Open Source", "DeFi"],
    eligibility: "Open to all developers, researchers, and designers worldwide",
    team_size: "2 - 4 Members",
    banner_image_url: "https://assets.devfolio.co/hackathons/2061a11b47c74daa90f2760db6c951f6/assets/cover/884.jpeg",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-21T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "devfolio-great-agent-hack",
    title: "The Great Agent Hackathon 2026",
    description: "Build autonomous multi-agent systems and LLM applications hosted on Devfolio. Integrate memory, tool calling, and workflow automation to solve complex enterprise problems.",
    type: "hackathon",
    source_platform: "Devfolio",
    source_url: "https://the-great-agent-hackathon.devfolio.co",
    organizer: "Devfolio & AI Ecosystem",
    location: "Online",
    mode: "online",
    start_date: "2026-09-15T00:00:00Z",
    end_date: "2026-10-05T23:59:59Z",
    application_deadline: "2026-09-12T18:29:59Z",
    prize_pool: "$25,000 in Bounties",
    stipend: null,
    tags: ["AI Agents", "LLMs", "LangChain", "Python", "Automation"],
    eligibility: "Global student hackers and engineers",
    team_size: "1 - 4 Members",
    banner_image_url: "https://assets.devfolio.co/hackathons/e6cecc553fb949c5a0b24ee56659b100/assets/cover/495.jpeg",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-22T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "h2skill-code-for-communities",
    title: "Build with AI: Code for Communities 2.0",
    description: "Powered by Hack2skill, this nationwide challenge focuses on building AI applications for healthcare, education accessibility, and smart city services. Selected teams receive GPU cloud credits and direct jury reviews.",
    type: "hackathon",
    source_platform: "H2Skill",
    source_url: "https://hack2skill.com/event/codeforcommunities2",
    organizer: "Hack2skill & Community Partners",
    location: "Online",
    mode: "online",
    start_date: "2026-09-15T00:00:00Z",
    end_date: "2026-09-30T23:59:59Z",
    application_deadline: "2026-09-10T18:29:59Z",
    prize_pool: "₹500,000 + Cloud Credits",
    stipend: null,
    tags: ["AI/ML", "Social Impact", "Python", "Cloud", "Open Source"],
    eligibility: "Open to all students, professionals, and independent hackers",
    team_size: "1 - 4 Members",
    banner_image_url: "https://storage.googleapis.com/vision-hack2skill-production/innovator/USER00000009/1788266976484-homepageAIBC1.webp",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-23T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "h2skill-ai-code-sarathi",
    title: "AI-Code Sarathi National Sprint",
    description: "AI-Code Sarathi brings together top developer talent to create AI-driven developer productivity tools, code intelligence assistants, and automated testing engines.",
    type: "hackathon",
    source_platform: "H2Skill",
    source_url: "https://hack2skill.com/event/ai-codesarathi",
    organizer: "Hack2skill",
    location: "Online",
    mode: "online",
    start_date: "2026-09-18T00:00:00Z",
    end_date: "2026-10-02T23:59:59Z",
    application_deadline: "2026-09-16T18:29:59Z",
    prize_pool: "₹300,000 + Mentorship",
    stipend: null,
    tags: ["DevTools", "GenAI", "Compilers", "Python", "Typescript"],
    eligibility: "Open to student developers and early-stage builders",
    team_size: "1 - 3 Members",
    banner_image_url: null,
    is_active: true,
    is_featured: false,
    created_at: "2026-08-24T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "unstop-code-quest-2026",
    title: "Code Quest 2026 — 21-Day Competitive Coding Challenge",
    description: "Join thousands of developers in solving algorithmic problems, competitive programming puzzles, and data structures challenges with direct recruiters viewing the leaderboard.",
    type: "hackathon",
    source_platform: "Unstop",
    source_url: "https://unstop.com/hackathons/code-quest-2026-21-day-competitive-coding-challenge-k-j-somaiya-institute-of-technology-kjsit-1743505",
    organizer: "KJSIT & Unstop",
    location: "Online",
    mode: "online",
    start_date: "2026-09-05T00:00:00Z",
    end_date: "2026-09-26T23:59:59Z",
    application_deadline: "2026-09-04T18:29:59Z",
    prize_pool: "₹100,000 + Certificates",
    stipend: null,
    tags: ["Competitive Programming", "C++", "Java", "Python", "Algorithms"],
    eligibility: "All undergraduate and postgraduate college students",
    team_size: "Individual",
    banner_image_url: null,
    is_active: true,
    is_featured: false,
    created_at: "2026-08-24T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "unstop-explore-internships-hub",
    title: "Software Engineering & Tech Internships Program",
    description: "Browse verified software engineering, full stack, machine learning, and frontend internship opportunities with leading tech companies and high-growth startups.",
    type: "internship",
    source_platform: "Unstop",
    source_url: "https://unstop.com/internships",
    organizer: "Verified Tech Recruiters on Unstop",
    location: "Bangalore / Remote, India",
    mode: "hybrid",
    start_date: "2026-10-01T00:00:00Z",
    end_date: "2027-04-30T23:59:59Z",
    application_deadline: "2026-09-28T18:29:59Z",
    prize_pool: null,
    stipend: "₹45,000 - ₹120,000 / month",
    tags: ["Software Engineering", "React", "Node.js", "Python", "Cloud"],
    eligibility: "B.Tech/B.E./MCA/M.Tech students graduating in 2025, 2026, or 2027",
    team_size: "Individual",
    banner_image_url: "https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/banner/6995f9362b8c4_inspiron-50.png",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-22T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "hackerearth-challenges-hub",
    title: "HackerEarth Global Hiring & Code Sprints",
    description: "Compete in monthly developer hiring challenges and coding assessments for top tier product companies. Solve algorithm challenges and submit system architectures.",
    type: "internship",
    source_platform: "HackerEarth",
    source_url: "https://www.hackerearth.com/challenges/",
    organizer: "HackerEarth Hiring Network",
    location: "Online / Global",
    mode: "online",
    start_date: "2026-09-10T00:00:00Z",
    end_date: "2026-10-31T23:59:59Z",
    application_deadline: "2026-09-20T18:29:59Z",
    prize_pool: null,
    stipend: "₹60,000 - ₹150,000 / month",
    tags: ["Backend", "Golang", "Java", "Distributed Systems", "Algorithms"],
    eligibility: "Pre-final / Final year students & working developers",
    team_size: "Individual",
    banner_image_url: "https://findmyrepovalue.hackerearth.com/og-image.png",
    is_active: true,
    is_featured: false,
    created_at: "2026-08-23T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  }
]

export const MOCK_COURSES: CourseRow[] = [
  {
    id: "fcc-responsive-web",
    title: "Responsive Web Design Certification",
    description: "Learn HTML and CSS fundamentals, modern CSS layout techniques including Flexbox and Grid, and build accessible, responsive websites from scratch.",
    provider: "freeCodeCamp",
    domain: "Web Development",
    level: "beginner",
    price_type: "free",
    price: null,
    duration: "~300 hours",
    certificate_provided: true,
    course_url: "https://www.freecodecamp.org/learn/2022/responsive-web-design",
    rating: 4.9,
    tags: ["HTML", "CSS", "Flexbox", "Grid", "Web Development"],
    is_active: true,
    is_featured: true,
    added_by: null,
    created_at: "2026-09-01T10:00:00Z",
    updated_at: "2026-09-01T10:00:00Z",
  },
  {
    id: "coursera-gemini-ai",
    title: "Getting Started with the Vertex AI Gemini 1.5 Pro Model",
    description: "Introductory, hands-on lab exploring Generative AI and prompt engineering with Gemini 1.5 Pro directly on Google Cloud console.",
    provider: "Coursera",
    domain: "AI/ML",
    level: "beginner",
    price_type: "free_with_paid_certificate",
    price: "$49",
    duration: "1 hour 30 mins",
    certificate_provided: true,
    course_url: "https://www.coursera.org/learn/googlecloud-getting-started-with-the-vertex-ai-gemini-1-5-pro-model-i43mr",
    rating: 4.8,
    tags: ["AI/ML", "Gemini", "Google Cloud", "Generative AI", "LLMs"],
    is_active: true,
    is_featured: true,
    added_by: null,
    created_at: "2026-09-02T10:00:00Z",
    updated_at: "2026-09-02T10:00:00Z",
  },
  {
    id: "fcc-javascript-dsa",
    title: "JavaScript Algorithms and Data Structures Certification",
    description: "Master fundamental JavaScript programming, OOP, functional programming, and algorithmic problem-solving techniques with classic data structures.",
    provider: "freeCodeCamp",
    domain: "DSA",
    level: "intermediate",
    price_type: "free",
    price: null,
    duration: "~300 hours",
    certificate_provided: true,
    course_url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8",
    rating: 4.9,
    tags: ["JavaScript", "Data Structures", "Algorithms", "DSA", "Problem Solving"],
    is_active: true,
    is_featured: true,
    added_by: null,
    created_at: "2026-09-03T10:00:00Z",
    updated_at: "2026-09-03T10:00:00Z",
  },
  {
    id: "nptel-intro-llms",
    title: "Introduction to Large Language Models (LLMs)",
    description: "Comprehensive college-level course offered by NPTEL and top IIT Delhi/Bombay faculty covering Transformer architectures, self-attention, pre-training, fine-tuning, and alignment.",
    provider: "NPTEL",
    domain: "AI/ML",
    level: "intermediate",
    price_type: "free_with_paid_certificate",
    price: "₹1,000",
    duration: "8-12 weeks",
    certificate_provided: true,
    course_url: "https://nptel.ac.in/courses/106102576",
    rating: 4.7,
    tags: ["NPTEL", "IIT Delhi", "IIT Bombay", "LLM", "Deep Learning", "AI/ML"],
    is_active: true,
    is_featured: true,
    added_by: null,
    created_at: "2026-09-04T10:00:00Z",
    updated_at: "2026-09-04T10:00:00Z",
  },
  {
    id: "udemy-100-days-python",
    title: "100 Days of Code: The Complete Python Pro Bootcamp",
    description: "Master Python by building 100 projects in 100 days. Learn data science, automation, building websites, games, and web apps with Python.",
    provider: "Udemy",
    domain: "Data Science",
    level: "beginner",
    price_type: "paid",
    price: "₹3,199",
    duration: "56 hours",
    certificate_provided: true,
    course_url: "https://www.udemy.com/course/100-days-of-code/",
    rating: 4.7,
    tags: ["Python", "Data Science", "Web Development", "Projects"],
    is_active: true,
    is_featured: true,
    added_by: null,
    created_at: "2026-09-05T10:00:00Z",
    updated_at: "2026-09-05T10:00:00Z",
  },
  {
    id: "udemy-aws-solutions-architect",
    title: "Ultimate AWS Certified Solutions Architect Associate 2026",
    description: "Full practice exam and comprehensive AWS architecture training covering EC2, S3, RDS, VPC, IAM, serverless, and cloud security.",
    provider: "Udemy",
    domain: "Cloud Computing",
    level: "intermediate",
    price_type: "paid",
    price: "₹3,299",
    duration: "27 hours",
    certificate_provided: true,
    course_url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
    rating: 4.7,
    tags: ["AWS", "Cloud Computing", "Architecture", "DevOps"],
    is_active: true,
    is_featured: true,
    added_by: null,
    created_at: "2026-09-06T10:00:00Z",
    updated_at: "2026-09-06T10:00:00Z",
  },
  {
    id: "fcc-infosec",
    title: "Information Security Certification",
    description: "Master cybersecurity principles, network security defenses, penetration testing, password cracking, and vulnerability scanning with Python and HelmetJS.",
    provider: "freeCodeCamp",
    domain: "Cybersecurity",
    level: "intermediate",
    price_type: "free",
    price: null,
    duration: "~300 hours",
    certificate_provided: true,
    course_url: "https://www.freecodecamp.org/learn/information-security-v7",
    rating: 4.8,
    tags: ["Cybersecurity", "Network Security", "Penetration Testing", "Python", "InfoSec"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-07T10:00:00Z",
    updated_at: "2026-09-07T10:00:00Z",
  },
  {
    id: "coursera-meta-frontend",
    title: "Meta Front-End Developer Professional Certificate",
    description: "Taught by Meta engineers. Master React, JavaScript, HTML, CSS, UI/UX principles, and prepare for entry-level front-end developer roles.",
    provider: "Coursera",
    domain: "Web Development",
    level: "beginner",
    price_type: "free_with_paid_certificate",
    price: "$49",
    duration: "7 months (6 hrs/wk)",
    certificate_provided: true,
    course_url: "https://www.coursera.org/professional-certificates/meta-front-end-developer",
    rating: 4.7,
    tags: ["React", "JavaScript", "HTML/CSS", "Meta", "Frontend"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "nptel-adv-distributed",
    title: "Advanced Distributed Systems",
    description: "Comprehensive graduate-level study of distributed algorithms, consensus protocols (Paxos, Raft), peer-to-peer systems, and fault tolerance by IIT Delhi faculty.",
    provider: "NPTEL",
    domain: "Cloud Computing",
    level: "advanced",
    price_type: "free_with_paid_certificate",
    price: "₹1,000",
    duration: "12 weeks",
    certificate_provided: true,
    course_url: "https://nptel.ac.in/courses/106102237",
    rating: 4.6,
    tags: ["Distributed Systems", "Cloud", "IIT Delhi", "NPTEL"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "udemy-master-coding-interview",
    title: "Master the Coding Interview: Data Structures + Algorithms",
    description: "Ultimate coding interview bootcamp. Ace technical interviews at FAANG companies by mastering Big O, trees, graphs, sorting, and dynamic programming.",
    provider: "Udemy",
    domain: "DSA",
    level: "intermediate",
    price_type: "paid",
    price: "₹3,199",
    duration: "19 hours",
    certificate_provided: true,
    course_url: "https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/",
    rating: 4.7,
    tags: ["DSA", "Algorithms", "Interview Prep", "Problem Solving"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "coursera-google-cybersecurity",
    title: "Google Cybersecurity Professional Certificate",
    description: "Prepare for an entry-level cybersecurity analyst job with hands-on practice in Linux, SQL, Python, SIEM tools, and network packet analysis from Google experts.",
    provider: "Google",
    domain: "Cybersecurity",
    level: "beginner",
    price_type: "free_with_paid_certificate",
    price: "$49",
    duration: "6 months (7 hrs/wk)",
    certificate_provided: true,
    course_url: "https://www.coursera.org/professional-certificates/google-cybersecurity",
    rating: 4.8,
    tags: ["Google", "Cybersecurity", "Python", "Linux", "SIEM", "SOC"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "fcc-data-analysis-python",
    title: "Data Analysis with Python Certification",
    description: "Process and analyze real-world datasets using NumPy, Pandas, Matplotlib, and Seaborn. Clean, transform, and visualize data like a professional data analyst.",
    provider: "freeCodeCamp",
    domain: "Data Science",
    level: "intermediate",
    price_type: "free",
    price: null,
    duration: "~300 hours",
    certificate_provided: true,
    course_url: "https://www.freecodecamp.org/learn/data-analysis-with-python-v7",
    rating: 4.8,
    tags: ["Python", "Pandas", "NumPy", "Data Analysis", "Data Science"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "aws-cloud-practitioner",
    title: "AWS Cloud Practitioner Essentials",
    description: "Official Amazon Web Services fundamental course for learning cloud concepts, security, architecture, pricing, and essential AWS services.",
    provider: "AWS Skill Builder",
    domain: "Cloud Computing",
    level: "beginner",
    price_type: "free",
    price: null,
    duration: "6 hours",
    certificate_provided: false,
    course_url: "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials",
    rating: 4.7,
    tags: ["AWS", "Cloud Computing", "Fundamentals", "Architecture"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "coursera-deeplearning-ai",
    title: "Deep Learning Specialization by Andrew Ng",
    description: "Master deep learning fundamentals, build neural networks with TensorFlow and Keras, train CNNs for computer vision, and understand transformers and sequence models.",
    provider: "Coursera",
    domain: "AI/ML",
    level: "intermediate",
    price_type: "free_with_paid_certificate",
    price: "$49",
    duration: "3 months (10 hrs/wk)",
    certificate_provided: true,
    course_url: "https://www.coursera.org/specializations/deep-learning",
    rating: 4.9,
    tags: ["Deep Learning", "Andrew Ng", "Neural Networks", "CNN", "RNN", "AI/ML"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "fcc-backend-apis",
    title: "Back End Development and APIs Certification",
    description: "Build backend applications and microservices using Node.js, npm, Express.js, and store persistent document data in MongoDB with Mongoose.",
    provider: "freeCodeCamp",
    domain: "Web Development",
    level: "intermediate",
    price_type: "free",
    price: null,
    duration: "~300 hours",
    certificate_provided: true,
    course_url: "https://www.freecodecamp.org/learn/back-end-development-and-apis",
    rating: 4.8,
    tags: ["Node.js", "Express", "MongoDB", "APIs", "Backend"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
  {
    id: "nptel-dsa-python",
    title: "Programming, Data Structures And Algorithms Using Python",
    description: "Rigorous algorithmic training course by IIT Madras covering search, sorting, divide-and-conquer, graph algorithms, stacks, queues, trees, and dynamic programming.",
    provider: "NPTEL",
    domain: "DSA",
    level: "intermediate",
    price_type: "free_with_paid_certificate",
    price: "₹1,000",
    duration: "8 weeks",
    certificate_provided: true,
    course_url: "https://nptel.ac.in/courses/106106145",
    rating: 4.6,
    tags: ["NPTEL", "Python", "DSA", "Algorithms", "IIT Madras"],
    is_active: true,
    is_featured: false,
    added_by: null,
    created_at: "2026-09-08T10:00:00Z",
    updated_at: "2026-09-08T10:00:00Z",
  },
]

