/**
 * lib/mockData.ts
 *
 * Real, active curated opportunities from Unstop, Devfolio, HackerEarth, and H2Skill.
 * Used as high-fidelity seed data when Supabase is not yet populated
 * so all "Apply Now" links redirect to live, active listings.
 */

import type { OpportunityRow } from "./supabase/types"

export const MOCK_OPPORTUNITIES: OpportunityRow[] = [
  {
    id: "unstop-buildsprint-ai",
    title: "BuildSprint 2026 — Next-Gen AI Hackathon",
    description: "BuildSprint is a fast-paced technology sprint organized on Unstop. Compete against top engineering teams to build cutting-edge solutions, AI agents, and full-stack platforms with mentorship and prize pools.",
    type: "hackathon",
    source_platform: "Unstop",
    source_url: "https://unstop.com/hackathons/buildsprint-latentforceai-1742504",
    organizer: "Latent Force AI & Unstop",
    location: "Online",
    mode: "online",
    start_date: "2026-09-01T00:00:00Z",
    end_date: "2026-10-15T23:59:59Z",
    application_deadline: "2026-09-30T18:29:59Z",
    prize_pool: "₹250,000 + Swags",
    stipend: null,
    tags: ["AI/ML", "Python", "Full Stack", "Cloud", "FastAPI"],
    eligibility: "Open to all engineering students and developers across India",
    team_size: "1 - 4 Members",
    banner_image_url: "https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/banner/6a83305e76ae6_hackcelestial-30.png",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-20T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "devfolio-fusionix-2026",
    title: "FusioniX 2026 — Asia's Premier Innovation Hackathon",
    description: "Join developers, designers, and builders for 36 hours of non-stop building at FusioniX on Devfolio. Build decentralized applications, zero-knowledge proofs, AI systems, and Web3 infrastructure with top mentors.",
    type: "hackathon",
    source_platform: "Devfolio",
    source_url: "https://fusionix-1.devfolio.co",
    organizer: "Devfolio Community",
    location: "Online / Hybrid",
    mode: "hybrid",
    start_date: "2026-10-10T09:00:00Z",
    end_date: "2026-10-12T18:00:00Z",
    application_deadline: "2026-09-25T18:29:59Z",
    prize_pool: "$50,000+",
    stipend: null,
    tags: ["Web3", "Solidity", "AI Agents", "Open Source", "DeFi"],
    eligibility: "Open to all developers, researchers, and designers worldwide",
    team_size: "2 - 4 Members",
    banner_image_url: "https://assets.devfolio.co/hackathons/2061a11b47c74daa90f2760db6c951f6/assets/cover/884.jpeg",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-21T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "devfolio-great-agent-hack",
    title: "The Great Agent Hackathon 2026",
    description: "Build autonomous multi-agent systems and LLM applications hosted on Devfolio. Integrate memory, tool calling, and workflow automation to solve complex enterprise problems.",
    type: "hackathon",
    source_platform: "Devfolio",
    source_url: "https://the-great-agent-hackathon.devfolio.co",
    organizer: "Devfolio & AI Ecosystem",
    location: "Online",
    mode: "online",
    start_date: "2026-09-15T00:00:00Z",
    end_date: "2026-10-05T23:59:59Z",
    application_deadline: "2026-09-12T18:29:59Z",
    prize_pool: "$25,000 in Bounties",
    stipend: null,
    tags: ["AI Agents", "LLMs", "LangChain", "Python", "Automation"],
    eligibility: "Global student hackers and engineers",
    team_size: "1 - 4 Members",
    banner_image_url: "https://assets.devfolio.co/hackathons/e6cecc553fb949c5a0b24ee56659b100/assets/cover/495.jpeg",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-22T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "h2skill-code-for-communities",
    title: "Build with AI: Code for Communities 2.0",
    description: "Powered by Hack2skill, this nationwide challenge focuses on building AI applications for healthcare, education accessibility, and smart city services. Selected teams receive GPU cloud credits and direct jury reviews.",
    type: "hackathon",
    source_platform: "H2Skill",
    source_url: "https://hack2skill.com/event/codeforcommunities2",
    organizer: "Hack2skill & Community Partners",
    location: "Online",
    mode: "online",
    start_date: "2026-09-15T00:00:00Z",
    end_date: "2026-09-30T23:59:59Z",
    application_deadline: "2026-09-10T18:29:59Z",
    prize_pool: "₹500,000 + Cloud Credits",
    stipend: null,
    tags: ["AI/ML", "Social Impact", "Python", "Cloud", "Open Source"],
    eligibility: "Open to all students, professionals, and independent hackers",
    team_size: "1 - 4 Members",
    banner_image_url: "https://storage.googleapis.com/vision-hack2skill-production/innovator/USER00000009/1788266976484-homepageAIBC1.webp",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-23T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "h2skill-ai-code-sarathi",
    title: "AI-Code Sarathi National Sprint",
    description: "AI-Code Sarathi brings together top developer talent to create AI-driven developer productivity tools, code intelligence assistants, and automated testing engines.",
    type: "hackathon",
    source_platform: "H2Skill",
    source_url: "https://hack2skill.com/event/ai-codesarathi",
    organizer: "Hack2skill",
    location: "Online",
    mode: "online",
    start_date: "2026-09-18T00:00:00Z",
    end_date: "2026-10-02T23:59:59Z",
    application_deadline: "2026-09-16T18:29:59Z",
    prize_pool: "₹300,000 + Mentorship",
    stipend: null,
    tags: ["DevTools", "GenAI", "Compilers", "Python", "Typescript"],
    eligibility: "Open to student developers and early-stage builders",
    team_size: "1 - 3 Members",
    banner_image_url: null,
    is_active: true,
    is_featured: false,
    created_at: "2026-08-24T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "unstop-code-quest-2026",
    title: "Code Quest 2026 — 21-Day Competitive Coding Challenge",
    description: "Join thousands of developers in solving algorithmic problems, competitive programming puzzles, and data structures challenges with direct recruiters viewing the leaderboard.",
    type: "hackathon",
    source_platform: "Unstop",
    source_url: "https://unstop.com/hackathons/code-quest-2026-21-day-competitive-coding-challenge-k-j-somaiya-institute-of-technology-kjsit-1743505",
    organizer: "KJSIT & Unstop",
    location: "Online",
    mode: "online",
    start_date: "2026-09-05T00:00:00Z",
    end_date: "2026-09-26T23:59:59Z",
    application_deadline: "2026-09-04T18:29:59Z",
    prize_pool: "₹100,000 + Certificates",
    stipend: null,
    tags: ["Competitive Programming", "C++", "Java", "Python", "Algorithms"],
    eligibility: "All undergraduate and postgraduate college students",
    team_size: "Individual",
    banner_image_url: null,
    is_active: true,
    is_featured: false,
    created_at: "2026-08-24T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "unstop-explore-internships-hub",
    title: "Software Engineering & Tech Internships Program",
    description: "Browse verified software engineering, full stack, machine learning, and frontend internship opportunities with leading tech companies and high-growth startups.",
    type: "internship",
    source_platform: "Unstop",
    source_url: "https://unstop.com/internships",
    organizer: "Verified Tech Recruiters on Unstop",
    location: "Bangalore / Remote, India",
    mode: "hybrid",
    start_date: "2026-10-01T00:00:00Z",
    end_date: "2027-04-30T23:59:59Z",
    application_deadline: "2026-09-28T18:29:59Z",
    prize_pool: null,
    stipend: "₹45,000 - ₹120,000 / month",
    tags: ["Software Engineering", "React", "Node.js", "Python", "Cloud"],
    eligibility: "B.Tech/B.E./MCA/M.Tech students graduating in 2025, 2026, or 2027",
    team_size: "Individual",
    banner_image_url: "https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/banner/6995f9362b8c4_inspiron-50.png",
    is_active: true,
    is_featured: true,
    created_at: "2026-08-22T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  },
  {
    id: "hackerearth-challenges-hub",
    title: "HackerEarth Global Hiring & Code Sprints",
    description: "Compete in monthly developer hiring challenges and coding assessments for top tier product companies. Solve algorithm challenges and submit system architectures.",
    type: "internship",
    source_platform: "HackerEarth",
    source_url: "https://www.hackerearth.com/challenges/",
    organizer: "HackerEarth Hiring Network",
    location: "Online / Global",
    mode: "online",
    start_date: "2026-09-10T00:00:00Z",
    end_date: "2026-10-31T23:59:59Z",
    application_deadline: "2026-09-20T18:29:59Z",
    prize_pool: null,
    stipend: "₹60,000 - ₹150,000 / month",
    tags: ["Backend", "Golang", "Java", "Distributed Systems", "Algorithms"],
    eligibility: "Pre-final / Final year students & working developers",
    team_size: "Individual",
    banner_image_url: "https://findmyrepovalue.hackerearth.com/og-image.png",
    is_active: true,
    is_featured: false,
    created_at: "2026-08-23T10:00:00Z",
    updated_at: "2026-08-24T12:00:00Z",
  }
]
